# Generated by Django 4.0.3 on 2022-12-09 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_soldcars_alter_sale_automobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='sales_rest.automobilevo'),
        ),
        migrations.DeleteModel(
            name='SoldCars',
        ),
    ]
