# Generated by Django 4.0.3 on 2022-12-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldcarsvo',
            name='import_href',
        ),
        migrations.AddField(
            model_name='soldcarsvo',
            name='import_id',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
