# Generated by Django 4.0.3 on 2022-12-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_remove_soldcarsvo_import_href_soldcarsvo_import_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldcarsvo',
            name='import_vin',
        ),
        migrations.AddField(
            model_name='soldcarsvo',
            name='vin',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
