# Generated by Django 4.0.3 on 2022-12-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_appointment_status_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TextField(),
        ),
    ]
