# Generated by Django 4.0.3 on 2022-12-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
