# Generated by Django 4.0.3 on 2022-12-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_remove_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('canceled', 'canceled'), ('finished', 'finished')], default='submitted', max_length=200),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
