# Generated by Django 4.0.3 on 2022-12-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_appointment_sold_here_alter_appointment_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
