# Generated by Django 4.0.3 on 2022-12-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0003_alter_vehiclemodel_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
